// ============================================================
//  Investment Portfolio — Stock Data
// ============================================================

export const AI_DEFAULTS = {
  'NTR':  { current_price: 70.62, pe_ratio: 18.4, risk: 'medium', buy_target: 64.00, sell_target: 85.00,
            notes: "World's largest fertiliser producer. Analyst median $79, Wells Fargo $100. Hormuz + China ban strong demand diversion." },
  'CF':   { pe_ratio: null, risk: 'high', buy_target: 88.00, sell_target: 120.00,
            notes: 'US urea & ammonia specialist. Targets raised: CIBC $128, RBC $125, Scotiabank $115. Pure-play urea surge beneficiary.' },
  'AMD':  { pe_ratio: 28.5, risk: 'medium', buy_target: 95.00, sell_target: 165.00,
            notes: 'Q1 2026: $10.3B rev (+38% YoY), Data Center $5.8B (+57%). Non-GAAP EPS $1.37. Q2 guide ~$11.2B (+46% YoY). MI450/Helios ramp, Meta 6GW deal, Samsung HBM4. Record FCF $2.57B.' },
  'INTC': { pe_ratio: null, risk: 'high', buy_target: 22.00, sell_target: 40.00,
            notes: 'Q1 2026: $13.58B rev (+7% YoY), DCAI $5.1B (+22%). Non-GAAP EPS $0.29 (vs $0.01 est). Q2 guide $13.8-14.8B. Stock +20% post-earnings (Apr 23). Turnaround play; Intel 18A ramp, Xeon 6 in NVIDIA DGX Rubin. Foundry loss -$2.4B.' },
  'SU':   { pe_ratio: 12.8, risk: 'medium', buy_target: 38.00, sell_target: 58.00,
            notes: "Canadian integrated oil sands major. Diversified upstream/downstream with Fort Hills & Base Plant. Strong FCF; disciplined buybacks. Upside on oil price recovery & operational efficiencies. Dividend yield ~5%." },
  'IREN': { pe_ratio: null, risk: 'high', buy_target: 7.00, sell_target: 18.00,
            notes: 'Iris Energy. Bitcoin mining + HPC/AI compute powered by 100% renewable energy. Data center expansion into AI workloads. High beta to BTC price & AI infrastructure demand.' },
  'SOBO': { pe_ratio: null, risk: 'high', buy_target: null, sell_target: null,
            notes: 'Energy sector. Hit AI Refresh Prices for current data and targets.' },
  'TRP':  { pe_ratio: 16.2, risk: 'medium', buy_target: 42.00, sell_target: 60.00,
            notes: 'TC Energy. Canadian natural gas pipeline giant. ~93,000 km network across North America. Dividend yield ~6%. Stable regulated cash flows; spun off liquids segment (South Bow). Long-term pipeline demand play.' },
  'ENB':  { pe_ratio: 18.5, risk: 'low', buy_target: 38.00, sell_target: 55.00,
            notes: "Enbridge. Canada's largest energy infrastructure company. Pipelines + regulated gas utilities. Dividend yield ~7%. 29 consecutive years of dividend growth. Highly defensive with long-term contracted cash flows." },
  'BTE':  { pe_ratio: null, risk: 'high', buy_target: 2.50, sell_target: 6.00,
            notes: 'Baytex Energy. Canadian oil & gas producer. Heavy oil (Lloydminster) + light oil (Eagle Ford, Pembina Duvernay). High leverage to oil price; strong FCF at $70+ WTI. Ongoing debt reduction post-Ranger acquisition.' },
  'OKLO': { pe_ratio: null, risk: 'vhigh', buy_target: 15.00, sell_target: 45.00,
            notes: 'Oklo Inc. Next-gen nuclear microreactor company. Sam Altman-backed. Targeting data center & defense power needs. Pre-revenue; Aurora fission powerhouse commercial deployment expected late 2020s. Speculative but high-conviction AI power theme.' },
  'D':    { pe_ratio: 19.4, risk: 'low', buy_target: 52.00, sell_target: 72.00,
            notes: 'Dominion Energy. Major US regulated electric & gas utility (Virginia, Carolinas). Dividend yield ~5%. Large offshore wind pipeline (CVOW). Rate-regulated business with predictable earnings. Defensive income play.' },
  'TXN':  { pe_ratio: 31.4, risk: 'low', buy_target: 145.00, sell_target: 220.00,
            notes: 'Texas Instruments. Analog & embedded chips for industrial, automotive, personal electronics. 80%+ revenue from industrial/auto — most defensive chip exposure. Owns its own fabs (LFAB, RFAB2) — cost advantage vs fabless peers. Dividend aristocrat, 20+ yrs consecutive raises. ~3% yield.' },
  'QCOM': { pe_ratio: 16.5, risk: 'medium', buy_target: 145.00, sell_target: 210.00,
            notes: 'Qualcomm. Snapdragon mobile SoCs + licensing (QTL). Diversifying aggressively: Auto revenue record $1.3B (+38% YoY) in Q2 FY2026, IoT +9%. FY2026 Q2: $10.6B revenue, EPS $2.65. Q3 guided $9.2-10B rev, auto +50% YoY. Returning $3.7B/qtr to shareholders.' },
  'TSM':  { pe_ratio: 29.0, risk: 'medium', buy_target: 160.00, sell_target: 240.00,
            notes: "Taiwan Semiconductor Manufacturing Co. World's #1 foundry — makes chips for Apple, NVIDIA, AMD, Qualcomm, Broadcom. 3nm in full production, 2nm ramping 2025. Every AI chip is fabbed at TSMC. Near-monopoly on leading-edge nodes. Dividend yield ~1.5%." },
  'VRT':  { pe_ratio: 42.1, risk: 'medium', buy_target: 90.00, sell_target: 160.00,
            notes: 'Vertiv Holdings. Data center power & thermal management — UPS, PDUs, cooling. Every AI data center needs Vertiv. Backlog at record highs, lead times extending. Direct play on hyperscaler capex surge. Raised guidance multiple times.' },
  'ALAB': { pe_ratio: null, risk: 'high', buy_target: 80.00, sell_target: 160.00,
            notes: 'Astera Labs. Semiconductor connectivity for AI/cloud data centers — PCIe retimers, CXL controllers, AEC cables. Designed into NVIDIA GB200 NVL72 racks. Fastest-growing AI infrastructure chip co. Revenue inflecting sharply as GB200 ramps.' },
  'CRDO': { pe_ratio: null, risk: 'high', buy_target: 40.00, sell_target: 85.00,
            notes: 'Credo Technology. High-speed connectivity ICs & active electrical cables for AI clusters. 800G/1.6T Ethernet for AI scale-out networks. Wins at major hyperscalers (Microsoft, Google). Growing rev >60% YoY.' },
  'ANET': { pe_ratio: 48.3, risk: 'medium', buy_target: 280.00, sell_target: 450.00,
            notes: 'Arista Networks. Cloud networking switches & software (EOS). Dominant in 400G/800G data center switching. AI back-end and front-end networking. Meta, Microsoft, Google are top customers. Recurring software revenue growing. Best-in-class margins ~35%.' },
  'NVT':  { pe_ratio: 22.8, risk: 'medium', buy_target: 55.00, sell_target: 90.00,
            notes: 'nVent Electric. Electrical enclosures, cable management & thermal solutions for data centers and industrial. Less hyped than Vertiv but similar exposure to data center buildout. Defense/industrial diversification provides stability.' },
  'PL':   { pe_ratio: null, risk: 'vhigh', buy_target: 3.50, sell_target: 9.00,
            notes: 'Planet Labs. Daily Earth imaging constellation (200+ satellites). AI analysis of satellite imagery — agriculture, climate, defense, supply chains. Government & defense contracts growing. Pre-profitability but unique dataset moat.' },
  'MU':   { pe_ratio: 11.2, risk: 'high', buy_target: 85.00, sell_target: 150.00,
            notes: 'Micron Technology. DRAM + NAND flash memory. #1 beneficiary of HBM3e demand for AI GPUs (NVIDIA H100/B200 need Micron HBM). Data center DRAM cycle turning up. HBM ASP 5-8x standard DRAM — massive margin expansion.' },
  'CLS':  { pe_ratio: 18.4, risk: 'medium', buy_target: 55.00, sell_target: 100.00,
            notes: 'Celestica (CLS / CLS.TO on TSX). Canadian EMS leader. AI server & networking hardware assembly for hyperscalers (Microsoft, Google, Meta). CCS segment growing 50%+ YoY. Transitioning from low-margin EMS to high-margin AI infrastructure.' },
  'WDC':  { pe_ratio: null, risk: 'high', buy_target: 45.00, sell_target: 85.00,
            notes: 'Western Digital. HDD (enterprise/cloud) + NAND flash. Spun off NAND business (Sandisk) — now pure-play HDD. Cloud HDD demand surging from AI data storage needs. Near-line HDD cycle early innings.' },
  'AMAT': { pe_ratio: 19.8, risk: 'medium', buy_target: 170.00, sell_target: 260.00,
            notes: 'Applied Materials. #1 semiconductor equipment maker globally. CVD, PVD, etch — tools needed to build every AI chip. HBM wafer fab expansion drives equipment orders. Gate-all-around (GAA) transition boosts AMAT content per wafer.' },
  'STX':  { pe_ratio: 14.6, risk: 'medium', buy_target: 90.00, sell_target: 140.00,
            notes: 'Seagate Technology. HDD #1 for nearline cloud storage. AI training datasets require massive cheap storage — HDD is the only viable medium at scale. Revenue recovery underway. Strong FCF, dividend ~3%.' },
  'TM':    { pe_ratio: 8.2, risk: 'medium', buy_target: 170.00, sell_target: 230.00,
             notes: 'Toyota Motor. Worlds largest automaker by volume. Hybrid dominance (Prius, RAV4) + aggressive EV push (bZ series). Strong FCF, disciplined capex. Yen weakness boosts USD earnings. Dividend yield ~3%.' },
  'MUFG':  { pe_ratio: 10.5, risk: 'medium', buy_target: 11.00, sell_target: 17.00,
             notes: "Mitsubishi UFJ Financial Group. Japan's largest bank by assets. Significant stake in Morgan Stanley. Beneficiary of BOJ rate normalization — rising rates expand NIM. Well-capitalized, growing international presence." },
  'SONY':  { pe_ratio: 17.3, risk: 'medium', buy_target: 90.00, sell_target: 130.00,
             notes: 'Sony Group. Diversified: PlayStation/gaming, music, movies, imaging sensors (global #1), financial services. PS5 cycle mature, PS6 upcoming. Sensor division critical for iPhone cameras. Resilient earnings mix.' },
  'HTHIY': { pe_ratio: 20.1, risk: 'medium', buy_target: 60.00, sell_target: 95.00,
             notes: 'Hitachi (OTC ADR). Industrial conglomerate pivoting to digital/IT services (Lumada platform). Rail systems, energy, construction machinery. High-margin transformation underway.' },
  'SFTBY': { pe_ratio: null, risk: 'high', buy_target: 22.00, sell_target: 40.00,
             notes: 'SoftBank Group (OTC ADR). Vision Fund vehicle for global tech bets (Arm, ByteDance affiliates, AI startups). Heavy discount to NAV historically. Arm Holdings stake is key value driver. High volatility, leveraged structure.' },
  'HMC':   { pe_ratio: 7.1, risk: 'medium', buy_target: 28.00, sell_target: 42.00,
             notes: 'Honda Motor. Autos + motorcycles (global #1) + power products. Joint EV development with Nissan. Robotics heritage (ASIMO). Attractive valuation; dividend yield ~4%.' },
  'IX':    { pe_ratio: 11.8, risk: 'low', buy_target: 95.00, sell_target: 140.00,
             notes: 'Orix Corporation. Diversified financial & industrial conglomerate. Leasing, banking, insurance, real estate, PE, aviation. Steady dividend grower. Undervalued vs. sum-of-parts.' },
  'SMFG':  { pe_ratio: 11.2, risk: 'medium', buy_target: 12.00, sell_target: 18.00,
             notes: "Sumitomo Mitsui Financial Group. Japan's 2nd largest bank. Rising domestic rates = NIM expansion tailwind. Strong capital ratios, growing overseas operations." },
  'TAK':   { pe_ratio: 22.4, risk: 'medium', buy_target: 13.00, sell_target: 20.00,
             notes: 'Takeda Pharmaceutical. Japans largest pharma. Focus areas: oncology, rare diseases, GI, neuroscience. Pipeline depth post-Shire acquisition. High debt from Shire, actively deleveraging. Dividend yield ~5%.' },
  'MFG':   { pe_ratio: 12.3, risk: 'medium', buy_target: 4.00, sell_target: 6.50,
             notes: "Mizuho Financial Group. Japan's 3rd largest bank. Retail, corporate & investment banking. BOJ policy normalization is structural tailwind. Improving ROE trajectory." },
  'FANUY': { pe_ratio: 28.5, risk: 'medium', buy_target: 22.00, sell_target: 38.00,
             notes: 'Fanuc. Global #1 in CNC systems & industrial robots. Dominant in factory automation. High margins (~30% operating). AI-driven manufacturing surge = structural tailwind. Conservative mgmt, net cash balance sheet.' },
  'NTDOY': { pe_ratio: 19.2, risk: 'medium', buy_target: 12.00, sell_target: 22.00,
             notes: 'Nintendo. Switch 2 launched 2025 — strongest IP portfolio in gaming (Mario, Zelda, Pokemon, Metroid). Net cash > $10B, zero debt. Theme parks (Universal) expanding. Consistent dividend + buybacks.' },
  'SHECY': { pe_ratio: 15.8, risk: 'low', buy_target: 28.00, sell_target: 45.00,
             notes: 'Shin-Etsu Chemical. Global #1 in silicon wafers (semiconductor substrates) and PVC. Near-oligopoly in wafers — every AI chip needs them. Extremely high margins, pristine balance sheet. Direct beneficiary of AI chip supercycle.' },
  'DKILY': { pe_ratio: 22.3, risk: 'low', buy_target: 18.00, sell_target: 32.00,
             notes: 'Daikin Industries. Global #1 in HVAC & refrigerants. Data centers need massive cooling — Daikin is a key supplier. Strong Asia growth (India, SEA). Expanding in heat pumps (Europe energy transition).' },
  'RCRUY': { pe_ratio: 24.7, risk: 'medium', buy_target: 7.00, sell_target: 13.00,
             notes: 'Recruit Holdings. Parent of Indeed & Glassdoor (global HR tech). Staffing business in Japan + global SaaS. Network effect moat in job listings. Growing international revenue. Consistent FCF growth.' },
  'BST':  { pe_ratio: null, risk: 'medium', buy_target: 32.00, sell_target: 50.00,
            notes: 'BlackRock Science & Technology Trust. Closed-end fund investing globally in science & tech leaders — AI, cloud, cybersecurity, semiconductors. Professionally managed by BlackRock with a strong distribution yield.' },
  'BSTZ': { pe_ratio: null, risk: 'medium', buy_target: 18.00, sell_target: 30.00,
            notes: 'BlackRock Science & Technology Trust II. Sister CEF to BST with a higher-growth mandate — emphasizes earlier-stage tech & science companies. Includes private company exposure alongside listed tech.' },
  'BTX':  { pe_ratio: null, risk: 'high', buy_target: null, sell_target: null,
            notes: 'BTX. Hit AI Refresh Prices to populate current data and analyst targets.' },
  'SSSS': { pe_ratio: null, risk: 'high', buy_target: 8.00, sell_target: 20.00,
            notes: 'SuRo Capital Corp. Publicly traded venture fund (BDC/CEF on Nasdaq) with ~36 private tech company holdings. Key positions include OpenAI, CoreWeave, Canva, Plaid, TensorWave, WHOOP, Lime, and Liquid Death. Q1 2026 NAV ~$9.18/share.' },
  'AGIX': { pe_ratio: null, risk: 'vhigh', buy_target: 0.40, sell_target: 2.00,
            notes: 'SingularityNET. Decentralized AI marketplace — developers publish, share, and monetize AI services via blockchain. Co-founded by Ben Goertzel (AGI pioneer). Merging with Fetch.ai and Ocean Protocol into ASI Alliance.' },
  '9984.T': { pe_ratio: null, risk: 'high', buy_target: 7000, sell_target: 18000,
              notes: "SoftBank Group Corp primary listing on Tokyo Stock Exchange (TSE: 9984), priced in JPY. Full exposure to the source — no ADR spread. Same underlying thesis: ~90% ARM ownership, SoftBank Vision Fund (AI/robotics/autonomy), and strategic OpenAI investment." },
  'FDX': { pe_ratio: 14.2, risk: 'low', buy_target: 300.00, sell_target: 400.00,
           notes: 'FedEx Corp. Global logistics giant — trucks, planes, warehouses. AI cannot deliver packages. Physical network moat. HALO thesis: irreplaceable hard assets. Goldman Sachs HALO basket top pick.' },
  'GE':  { pe_ratio: 38.5, risk: 'medium', buy_target: 280.00, sell_target: 400.00,
           notes: 'GE Aerospace. Jet engine manufacturer with $190B order backlog. Goldman Sachs March 2026 Conviction List. Supply cannot meet demand for years. LEAP and GE9X engines power most commercial aircraft.' },
  'KO':  { pe_ratio: 23.1, risk: 'low', buy_target: 70.00, sell_target: 95.00,
           notes: "Coca-Cola. Global brand + physical distribution network across 200+ countries. No AI agent can replace bottling plants and delivery routes. Dividend King (62+ yrs consecutive raises). Defensive HALO anchor." },
  'UNP': { pe_ratio: 22.4, risk: 'low', buy_target: 245.00, sell_target: 310.00,
           notes: 'Union Pacific Railroad. 32,000 miles of rail across the western US — physically impossible to replicate. Moves coal, grain, autos, and intermodal freight. 160-year right-of-way moat. Dividend grower ~2.5% yield.' },
  'RTX': { pe_ratio: 34.1, risk: 'low', buy_target: 168.00, sell_target: 215.00,
           notes: 'RTX Corp (formerly Raytheon Technologies). Pratt & Whitney jet engines + Patriot missiles + Stinger air-defense systems. $200B+ backlog. Decades-long defense contracts. Physical manufacturing complexity AI cannot shortcut.' },
  'WM':  { pe_ratio: 32.8, risk: 'low', buy_target: 205.00, sell_target: 260.00,
           notes: 'Waste Management Inc. Largest US waste/recycling company — 26M customers, 260 landfills, 5,700 trucks. AI cannot pick up trash. Essential recession-proof service with a regulated landfill moat.' },
  'CAT': { pe_ratio: 17.9, risk: 'medium', buy_target: 840.00, sell_target: 1050.00,
           notes: 'Caterpillar Inc. Dominant heavy equipment maker — excavators, bulldozers, mining trucks. Builds the machines that build everything else. AI boom drives data center construction = more CAT demand. Dividend aristocrat, 30+ consecutive years of raises.' },
  'NEE': { pe_ratio: 21.2, risk: 'low', buy_target: 82.00, sell_target: 108.00,
           notes: "NextEra Energy. Largest US electric utility + world's largest wind/solar operator. Physical power grid in Florida (FPL) + massive regulated renewable assets. AI data centers are the biggest new power customers — NextEra supplies the electrons." },
  'QUBT': { pe_ratio: null, risk: 'vhigh', buy_target: 7.00, sell_target: 20.00,
            notes: 'Quantum Computing Inc. Quantum optimization software + photonics. NASA & US Gov contracts. Early-stage, pre-revenue. High-risk speculative play.' },
  'QBTS': { pe_ratio: null, risk: 'high', buy_target: 2.50, sell_target: 8.00,
            notes: 'D-Wave Quantum. Quantum annealing hardware + cloud. Real commercial customers in logistics & finance. Most mature revenue of pure-play quantum names.' },
  'RGTI': { pe_ratio: null, risk: 'high', buy_target: 3.00, sell_target: 10.00,
            notes: 'Rigetti Computing. Full-stack quantum hardware & software. Cloud access via AWS & Azure. Still cash-burn stage; multi-qubit roadmap progressing.' },
  'QTUM': { pe_ratio: null, risk: 'medium', buy_target: 18.00, sell_target: 40.00,
            notes: 'Direxion Quantum Computing ETF. Diversified exposure across quantum hardware, software & enablers. Lowest risk in the quantum basket — ETF structure smooths individual name volatility.' },
  'IONQ': { pe_ratio: null, risk: 'vhigh', buy_target: 25.00, sell_target: 80.00,
            notes: 'IonQ. Trapped-ion quantum computing pure-play. Government & commercial contracts. Pre-profitability; every milestone (qubit fidelity, error correction) is a catalyst. Highest-conviction quantum hardware bet on the market.' },
  'PLTR': { pe_ratio: null, risk: 'high', buy_target: 70.00, sell_target: 180.00,
            notes: 'Palantir Technologies. AI/data analytics platform for US government (Gotham) and commercial (Foundry, AIP). Deep defense & intelligence contracts. AIP commercial adoption accelerating.' },
  'RKLB': { pe_ratio: null, risk: 'high', buy_target: 15.00, sell_target: 50.00,
            notes: 'Rocket Lab. Small satellite launch (Electron) + space systems manufacturing (Neutron in development). Growing launch cadence; Photon spacecraft platform. Only credible sub-scale alternative to SpaceX.' },
  'CRWV': { pe_ratio: null, risk: 'high', buy_target: 40.00, sell_target: 110.00,
            notes: "CoreWeave. AI cloud infrastructure — rents Nvidia GPU clusters to AI labs and enterprises. NVIDIA-backed, Microsoft as anchor customer. Recently IPO'd. Fastest-growing AI cloud provider but heavily debt-financed." },
  'APLD': { pe_ratio: null, risk: 'vhigh', buy_target: 6.00, sell_target: 20.00,
            notes: 'Applied Digital. Builds & operates HPC and AI data centers. Early mover in purpose-built AI infrastructure. Capital-intensive and cash-burning, but data center leases provide revenue visibility.' },
  'HOOD': { pe_ratio: null, risk: 'high', buy_target: 25.00, sell_target: 65.00,
            notes: 'Robinhood Markets. Retail brokerage expanding into crypto, prediction markets, and banking products. User base growing; ARPU inflecting higher. Benefits from high retail trading volumes.' },
  'HIMS': { pe_ratio: null, risk: 'high', buy_target: 18.00, sell_target: 55.00,
            notes: 'Hims & Hers Health. Telehealth platform — hair loss, ED, mental health, weight loss (GLP-1). Compounded semaglutide drove explosive growth. FDA compounding rules are the key risk.' },
  'CVNA': { pe_ratio: null, risk: 'high', buy_target: 150.00, sell_target: 380.00,
            notes: 'Carvana. Online used car dealer that staged a dramatic comeback from near-bankruptcy. Improving unit economics and EBITDA margins. Still carries significant debt.' },
  'MSTR': { pe_ratio: null, risk: 'vhigh', buy_target: 300.00, sell_target: 750.00,
            notes: 'Strategy (formerly MicroStrategy). The ultimate leveraged Bitcoin proxy — holds ~214K BTC on balance sheet funded via equity/debt issuance. Trades at a significant premium to NAV.' },
  'JOBY': { pe_ratio: null, risk: 'vhigh', buy_target: 5.00, sell_target: 18.00,
            notes: 'Joby Aviation. Electric air taxi (eVTOL) company backed by Toyota and Delta Air Lines. FAA certification in progress; targeting commercial launch mid-2020s. Pre-revenue, cash-burning.' },
  'NBIS': { pe_ratio: null, risk: 'vhigh', buy_target: 10.00, sell_target: 35.00,
            notes: 'Nebius Group. European AI cloud infrastructure company spun out of Yandex. NVIDIA-backed; building GPU clusters for AI workloads across Europe.' },
  'RIVN': { pe_ratio: null, risk: 'high', buy_target: 10.00, sell_target: 35.00,
            notes: 'Rivian Automotive. EV truck & van maker with Amazon as a major fleet customer (100K van order). R1T/R1S consumer lineup gaining traction. Volkswagen strategic partnership adds credibility.' },
  'SYM':  { pe_ratio: null, risk: 'high', buy_target: 15.00, sell_target: 50.00,
            notes: 'Symbotic. AI-powered warehouse robotics and automation. Walmart-backed with long-term deployment contract across thousands of distribution centers. Platform revenue model with recurring software layer.' },
  'SWMR': { pe_ratio: null, risk: 'vhigh', buy_target: 30.00, sell_target: 70.00,
            notes: 'Swarmer. Drone autonomy software provider. Surged 223% YTD before pulling back ~46% from $83 peak. Record backlog signals strong demand. Extremely high valuation — pure speculative momentum play on the drone/AI autonomy theme.' },
  // Space Portfolio
  'SPCE': { pe_ratio: null, risk: 'vhigh', buy_target: 5.00,  sell_target: 20.00,
            notes: 'Virgin Galactic. Space tourism company flying paying passengers to suborbital space. Very early market; extremely high burn rate. Speculative long-term bet on commercial space tourism.' },
  'HONA': { pe_ratio: null, risk: 'low', buy_target: null, sell_target: null,
            notes: 'Honeywell Aerospace Inc. Spinoff from HON, distributed 29/6/2026 (1 HONA per 2 HON). $17B+ annual revenue. Global installed base across commercial & defense aircraft. NASDAQ:HONA. Price TBD — stock begins trading 29 June 2026.' },
  'LUNR': { pe_ratio: null, risk: 'vhigh', buy_target: 6.00,  sell_target: 20.00,
            notes: 'Intuitive Machines. NASA-contracted lunar lander and services provider. Direct beneficiary of Artemis program. IM-1 mission landed on lunar south pole. Revenue tied to NASA CLPS contracts. Pre-profitability but growing backlog.' },
  'ASTS': { pe_ratio: null, risk: 'high',  buy_target: 20.00, sell_target: 60.00,
            notes: 'AST SpaceMobile. Building a space-based cellular broadband network connecting standard mobile phones directly via satellite. Partnerships with AT&T, Vodafone, Rakuten. BlueBird constellation deployment underway.' },
  'KTOS': { pe_ratio: null, risk: 'medium', buy_target: 45.00, sell_target: 120.00,
            notes: 'Kratos Defense & Security Solutions. Tactical drones (Valkyrie XQ-58A), hypersonics, satellite ground systems. KeyBanc top aerospace & defense pick 2026, PT $100-125 (+60% upside). First-to-market in collaborative combat aircraft + counter-drone. US-Iran tensions & NATO budget hikes are structural tailwinds. Stock +196% in 2025.' },
  'SPCX': { pe_ratio: null, risk: 'high',  buy_target: 135.00, sell_target: 250.00,
            notes: "SpaceX. IPO'd June 12, 2026 at $135; closed day-1 at $161 (+19%) — largest IPO in history. Operates Starlink satellite internet (>7M subscribers), Falcon 9/Heavy rockets, and Starship. Near-monopoly on commercial orbital launch." },
  'RDW':  { pe_ratio: null, risk: 'high',  buy_target: 12.00, sell_target: 30.00,
            notes: 'Redwire Corporation. Space infrastructure manufacturer — solar arrays, deployable structures, in-space manufacturing. NATO and US Army contracts. Q1 2026 revenue $97M (+58% YoY), record backlog $498M. Golden Dome upside.' },
  // ── Cybersecurity ────────────────────────────────────────────────────────
  'CRWD': { pe_ratio: null, risk: 'high', buy_target: 600.00, sell_target: 820.00,
            notes: 'CrowdStrike. AI-native endpoint & cloud security platform (Falcon). Every cyberattack begins at an endpoint — CRWD has runtime kernel presence across 30K+ enterprise customers. Revenue +25% YoY, 97%+ gross retention. Morgan Stanley Buy, $510 PT (legacy) — stock re-rated higher on AI threat tailwind. Premier cybersecurity play.' },
  'PANW': { pe_ratio: null, risk: 'medium', buy_target: 250.00, sell_target: 360.00,
            notes: 'Palo Alto Networks. Largest pure-play cybersecurity platform — NGFW, SASE, Cortex AI. Platformization strategy winning: enterprises consolidating 5-10 point tools onto PANW. Morgan Stanley Buy, ~$220-285 PT range. Billings growing ~15% YoY. Best platform breadth in the sector.' },

  // ── Nuclear & Clean Power ────────────────────────────────────────────────
  'CEG':  { pe_ratio: 29.8, risk: 'low', buy_target: 235.00, sell_target: 340.00,
            notes: 'Constellation Energy. Largest US nuclear fleet operator (21 reactors, ~21 GW capacity). Signed long-term power agreements with Microsoft (Three Mile Island restart) and Google. AI data centers need 24/7 carbon-free baseload — nuclear is the only answer at scale. 14/15 analysts Buy.' },
  'VST':  { pe_ratio: 22.4, risk: 'medium', buy_target: 145.00, sell_target: 230.00,
            notes: 'Vistra Corp. Largest competitive power generator in the US (nuclear + gas + solar). Texas ERCOT grid exposure benefits from data center boom. 12/12 analysts Buy. Energy transition + AI power demand = structural tailwind. Higher beta nuclear play vs CEG.' },

  // ── Robotics / AI Hardware ───────────────────────────────────────────────
  'TSLA': { pe_ratio: null, risk: 'high', buy_target: 340.00, sell_target: 580.00,
            notes: 'Tesla. EV + Energy Storage + Optimus humanoid robot. Fremont factory converting to Optimus production. Jensen Huang calls humanoid robots a $40T market. Figure AI BotQ = 1 robot/hr (June 2026); Tesla targeting Optimus Gen 3 summer launch. FSD autonomous driving subscription revenue growing. Long thesis: robotics ramp 2027+.' },

};

// Last iv-check snapshot: 2026-06-16 22:29 UTC
export const PRICE_UPDATES = {
  'NTR':   { current_price: 65.48,   day_change_pct: -0.98  },
  'BST':   { current_price: 48.05,   day_change_pct: -0.33  },
  'BSTZ':   { current_price: 30.86,   day_change_pct: -2.59  },
  'BTX':   { current_price: 9.16,   day_change_pct: -2.03  },
  'AGIX':   { current_price: 46.82,   day_change_pct: -1.37  },
  'CF':   { current_price: 105.59,   day_change_pct: -1.23  },
  'AMD':   { current_price: 507.29,   day_change_pct: -7.3  },
  'INTC':   { current_price: 117.05,   day_change_pct: -8.45  },
  'TXN':   { current_price: 305.71,   day_change_pct: -2.44  },
  'QCOM':   { current_price: 214.07,   day_change_pct: -3.05  },
  'SU':   { current_price: 58.16,   day_change_pct: -2.5  },
  'IREN':   { current_price: 59.18,   day_change_pct: -2.74  },
  'SOBO':   { current_price: 36.95,   day_change_pct: -1.81  },
  'TRP':   { current_price: 68.92,   day_change_pct: -0.22  },
  'ENB':   { current_price: 55.68,   day_change_pct: -0.46  },
  'BTE':   { current_price: 4.22,   day_change_pct: -3.87  },
  'OKLO':   { current_price: 57.45,   day_change_pct: -5.42  },
  'D':   { current_price: 68.5,   day_change_pct: +0.51  },
  'QUBT':   { current_price: 10.12,   day_change_pct: -8.83  },
  'QBTS':   { current_price: 23.94,   day_change_pct: -8.83  },
  'RGTI':   { current_price: 20.64,   day_change_pct: -9.07  },
  'QTUM':   { current_price: 162.28,   day_change_pct: -3.43  },
  'CLS':   { current_price: 382.01,   day_change_pct: -5.31  },
  'VRT':   { current_price: 299.6,   day_change_pct: -3.95  },
  'ALAB':   { current_price: 361.71,   day_change_pct: -7.06  },
  'CRDO':   { current_price: 239.18,   day_change_pct: -7.8  },
  'ANET':   { current_price: 168.01,   day_change_pct: -0.64  },
  'NVT':   { current_price: 167.34,   day_change_pct: -0.98  },
  'PL':   { current_price: 28.21,   day_change_pct: -7.75  },
  'MU':   { current_price: 1020.76,   day_change_pct: -6.18  },
  'WDC':   { current_price: 681.08,   day_change_pct: +4.22  },
  'AMAT':   { current_price: 568.23,   day_change_pct: -3.0  },
  'STX':   { current_price: 1031.34,   day_change_pct: +1.23  },
  'TM':   { current_price: 178.19,   day_change_pct: -1.13  },
  'MUFG':   { current_price: 20.3,   day_change_pct: +0.59  },
  'SONY':   { current_price: 20.38,   day_change_pct: -0.1  },
  'HTHIY':   { current_price: 29.8,   day_change_pct: +0.81  },
  'SFTBY':   { current_price: 21.9,   day_change_pct: -5.07  },
  'HMC':   { current_price: 26.85,   day_change_pct: -0.44  },
  'IX':   { current_price: 39.37,   day_change_pct: +2.5  },
  'SMFG':   { current_price: 24.17,   day_change_pct: -0.53  },
  'MFG':   { current_price: 9.76,   day_change_pct: +0.83  },
  'FANUY':   { current_price: 22.96,   day_change_pct: +0.26  },
  'NTDOY':   { current_price: 11.2,   day_change_pct: +1.54  },
  'SHECY':   { current_price: 23.14,   day_change_pct: -1.7  },
  'DKILY':   { current_price: 14.67,   day_change_pct: +1.17  },
  'RCRUY':   { current_price: 13.38,   day_change_pct: +0.22  },
  'TAK':   { current_price: 15.66,   day_change_pct: -0.7  },
  'FDX':   { current_price: 335.74,   day_change_pct: -0.89  },
  'GE':   { current_price: 351.73,   day_change_pct: +2.77  },
  'KO':   { current_price: 80.28,   day_change_pct: -0.78  },
  'UNP':   { current_price: 267.45,   day_change_pct: +0.05  },
  'RTX':   { current_price: 186.77,   day_change_pct: +1.7  },
  'WM':   { current_price: 218.59,   day_change_pct: +0.76  },
  'CAT':   { current_price: 945.46,   day_change_pct: +1.23  },
  'NEE':   { current_price: 86.23,   day_change_pct: +0.13  },
  'IONQ':   { current_price: 56.06,   day_change_pct: -8.37  },
  'PLTR':   { current_price: 133.25,   day_change_pct: -1.08  },
  'RKLB':   { current_price: 104.63,   day_change_pct: -4.23  },
  'CRWV':   { current_price: 117.03,   day_change_pct: +9.67  },
  'APLD':   { current_price: 46.27,   day_change_pct: -0.43  },
  'NBIS':   { current_price: 265.1,   day_change_pct: +1.93  },
  'RIVN':   { current_price: 15.93,   day_change_pct: -4.5  },
  'SYM':   { current_price: 40.81,   day_change_pct: -2.18  },
  'SWMR':   { current_price: 41.4,   day_change_pct: -1.33  },
  'SSSS':   { current_price: 13.02,   day_change_pct: -3.98  },
  'CRWD':  { current_price: 675.44,  day_change_pct: 0.0  },
  'PANW':  { current_price: 286.40,  day_change_pct: 0.0  },
  'CEG':   { current_price: 275.53,  day_change_pct: 0.0  },
  'VST':   { current_price: 167.26,  day_change_pct: 0.0  },
  'TSLA':  { current_price: 405.05,  day_change_pct: 0.0  },
  'TSM':   { current_price: 425.83,   day_change_pct: -3.53  },
};
