import { AI_DEFAULTS, PRICE_UPDATES } from './data';

export const PALETTE = ['#0ea5e9','#7c3aed','#10b981','#f59e0b','#ef4444','#6366f1','#ec4899','#14b8a6'];

function makeStock(ticker, company, sector, alloc_pct = null) {
  const def = AI_DEFAULTS[ticker] || {};
  return {
    ticker, company, sector,
    alloc_pct,
    buy_price: null,
    current_price: PRICE_UPDATES[ticker]?.current_price ?? def.current_price ?? null,
    day_change_pct: PRICE_UPDATES[ticker]?.day_change_pct ?? null,
    pe_ratio: def.pe_ratio ?? null,
    risk: def.risk ?? null,
    buy_target: def.buy_target ?? null,
    sell_target: def.sell_target ?? null,
    notes: def.notes ?? '',
  };
}

const LAST_REFRESH = new Date().toISOString();

export const INITIAL_PORTFOLIOS = [
  {
    id: 'p-ai-infra',
    name: 'AI Infrastructure',
    color: '#7c3aed',
    lastRefresh: LAST_REFRESH,
    dataSource: 'yahoo+ai',
    stocks: [
      makeStock('AMD',  'Advanced Micro Devices', 'semiconductor', 50),
      makeStock('INTC', 'Intel Corporation',      'semiconductor', 50),
      makeStock('CLS',  'Celestica',              'semiconductor', null),
      makeStock('VRT',  'Vertiv Holdings',        'semiconductor', null),
      makeStock('ALAB', 'Astera Labs',            'semiconductor', null),
      makeStock('CRDO', 'Credo Technology',       'semiconductor', null),
      makeStock('ANET', 'Arista Networks',        'semiconductor', null),
      makeStock('NVT',  'nVent Electric',         'semiconductor', null),
      makeStock('PL',   'Planet Labs',            'tech',          null),
    ],
  },
  {
    id: 'p-chip',
    name: 'CHIP',
    color: '#6366f1',
    lastRefresh: LAST_REFRESH,
    dataSource: 'yahoo+ai',
    stocks: [
      makeStock('AMD',  'Advanced Micro Devices',         'semiconductor', null),
      makeStock('INTC', 'Intel Corporation',              'semiconductor', null),
      makeStock('TXN',  'Texas Instruments',              'semiconductor', null),
      makeStock('QCOM', 'Qualcomm',                       'semiconductor', null),
      makeStock('TSM',  'Taiwan Semiconductor Mfg.',      'semiconductor', null),
    ],
  },
  {
    id: 'p-energy',
    name: 'Energy',
    color: '#f59e0b',
    lastRefresh: LAST_REFRESH,
    dataSource: 'yahoo+ai',
    stocks: [
      makeStock('SU',   'Suncor Energy Inc.',   'energy', null),
      makeStock('IREN', 'Iris Energy',          'energy', null),
      makeStock('SOBO', 'SOBO',                 'energy', null),
      makeStock('TRP',  'TC Energy',            'energy', null),
      makeStock('ENB',  'Enbridge',             'energy', null),
      makeStock('BTE',  'Baytex Energy',        'energy', null),
      makeStock('OKLO', 'Oklo Inc.',            'energy', null),
      makeStock('D',    'Dominion Energy',      'energy', null),
    ],
  },
  {
    id: 'p-memory',
    name: 'Memory & Storage',
    color: '#0891b2',
    lastRefresh: LAST_REFRESH,
    dataSource: 'yahoo+ai',
    stocks: [
      makeStock('MU',   'Micron Technology',    'semiconductor', 25),
      makeStock('CLS',  'Celestica (CLS.TO)',   'semiconductor', 20),
      makeStock('WDC',  'Western Digital',      'tech',          20),
      makeStock('AMAT', 'Applied Materials',    'semiconductor', 20),
      makeStock('STX',  'Seagate Technology',   'tech',          15),
    ],
  },
  {
    id: 'p-japan',
    name: 'Japanese Stocks',
    color: '#dc2626',
    lastRefresh: LAST_REFRESH,
    dataSource: 'yahoo+ai',
    stocks: [
      makeStock('TM',    'Toyota Motor',              'auto',         12),
      makeStock('MUFG',  'Mitsubishi UFJ Financial',  'finance',      10),
      makeStock('SONY',  'Sony Group',                'tech',         12),
      makeStock('HTHIY', 'Hitachi',                   'conglomerate', 10),
      makeStock('SFTBY', 'SoftBank Group',            'tech',          8),
      makeStock('HMC',   'Honda Motor',               'auto',         10),
      makeStock('IX',    'Orix Corporation',          'conglomerate', 10),
      makeStock('SMFG',  'Sumitomo Mitsui Financial', 'finance',      10),
      makeStock('MFG',   'Mizuho Financial Group',    'finance',      10),
      makeStock('FANUY', 'Fanuc',                     'conglomerate', null),
      makeStock('NTDOY', 'Nintendo',                  'tech',         null),
      makeStock('SHECY', 'Shin-Etsu Chemical',        'semiconductor',null),
      makeStock('DKILY', 'Daikin Industries',         'other',        null),
      makeStock('RCRUY', 'Recruit Holdings',          'tech',         null),
    ],
  },
  {
    id: 'p-quantum',
    name: 'Quantum Computing',
    color: '#4338ca',
    lastRefresh: LAST_REFRESH,
    dataSource: 'yahoo+ai',
    stocks: [
      makeStock('QUBT', 'Quantum Computing Inc.', 'quantum', 25),
      makeStock('QBTS', 'D-Wave Quantum',          'quantum', 25),
      makeStock('RGTI', 'Rigetti Computing',       'quantum', 25),
      makeStock('QTUM', 'Direxion Quantum ETF',    'etf',     25),
    ],
  },
  {
    id: 'p-ai-superstar',
    name: 'AI SuperStar',
    color: '#f59e0b',
    lastRefresh: LAST_REFRESH,
    dataSource: 'yahoo+ai',
    stocks: [
      makeStock('BST',    'BlackRock Science & Technology Trust',    'etf',     15),
      makeStock('BSTZ',   'BlackRock Science & Technology Trust II', 'etf',     15),
      makeStock('BTX',    'BTX',                                     'tech',    14),
      makeStock('AGIX',   'SingularityNET',                          'tech',    14),
      makeStock('SSSS',   'SuRo Capital Corp.',                      'finance', 14),
      makeStock('SFTBY',  'SoftBank Group Corp. (ADR)',              'tech',    14),
      makeStock('9984.T', 'SoftBank Group Corp. (Tokyo)',            'tech',    14),
    ],
  },
  {
    id: 'p-high-risk',
    name: 'High Risk',
    color: '#ef4444',
    lastRefresh: LAST_REFRESH,
    dataSource: 'yahoo+ai',
    stocks: [
      makeStock('IONQ', 'IonQ',                 'quantum', 12),
      makeStock('PLTR', 'Palantir Technologies', 'tech',    12),
      makeStock('RKLB', 'Rocket Lab',            'tech',    11),
      makeStock('CRWV', 'CoreWeave',             'tech',    11),
      makeStock('APLD', 'Applied Digital',       'tech',    11),
      makeStock('NBIS', 'Nebius Group',          'tech',    11),
      makeStock('RIVN', 'Rivian Automotive',     'auto',    11),
      makeStock('SYM',  'Symbotic',              'tech',    11),
      makeStock('SWMR', 'Swarmer Inc.',          'drone',   10),
    ],
  },
  {
    id: 'p-defense-halo',
    name: 'Defense HALO',
    color: '#1a3a5c',
    lastRefresh: LAST_REFRESH,
    dataSource: 'yahoo+ai',
    stocks: [
      makeStock('FDX', 'FedEx Corp',             'logistics', 20),
      makeStock('GE',  'GE Aerospace',           'aerospace', 16),
      makeStock('KO',  'Coca-Cola',              'staples',   16),
      makeStock('UNP', 'Union Pacific Railroad', 'logistics', 16),
      makeStock('RTX', 'RTX Corp',              'aerospace', 12),
      makeStock('WM',  'Waste Management Inc.', 'other',      8),
      makeStock('CAT', 'Caterpillar Inc.',       'other',      8),
      makeStock('NEE', 'NextEra Energy',         'energy',     4),
    ],
  },
  {
    id: 'p-space',
    name: 'Space',
    color: '#0f172a',
    lastRefresh: LAST_REFRESH,
    dataSource: 'yahoo+ai',
    stocks: [
      makeStock('SPCX', 'SpaceX',              'space',   20),
      makeStock('RKLB', 'Rocket Lab',          'space',   16),
      makeStock('ASTS', 'AST SpaceMobile',     'space',   16),
      makeStock('KTOS', 'Kratos Defense',      'defense', 14),
      makeStock('RDW',  'Redwire Corporation', 'space',   14),
      makeStock('LUNR', 'Intuitive Machines',  'space',   12),
      makeStock('SPCE', 'Virgin Galactic',     'space',    8),
      makeStock('HONA', 'Honeywell Aerospace', 'aerospace', null),
    ],
  },
  {
    id: 'p-cybersecurity',
    name: 'Cybersecurity',
    color: '#059669',
    lastRefresh: LAST_REFRESH,
    dataSource: 'yahoo+ai',
    stocks: [
      makeStock('CRWD', 'CrowdStrike',        'cybersecurity', 50),
      makeStock('PANW', 'Palo Alto Networks', 'cybersecurity', 50),
    ],
  },
  {
    id: 'p-nuclear-power',
    name: 'Nuclear & Clean Power',
    color: '#b45309',
    lastRefresh: LAST_REFRESH,
    dataSource: 'yahoo+ai',
    stocks: [
      makeStock('CEG',  'Constellation Energy', 'energy', 40),
      makeStock('VST',  'Vistra Corp',           'energy', 35),
      makeStock('OKLO', 'Oklo Inc.',             'energy', 25),
    ],
  },
  {
    id: 'p-robotics',
    name: 'Robotics & AI Hardware',
    color: '#7c3aed',
    lastRefresh: LAST_REFRESH,
    dataSource: 'yahoo+ai',
    stocks: [
      makeStock('TSLA',  'Tesla',        'auto',          40),
      makeStock('QCOM',  'Qualcomm',     'semiconductor', 30),
      makeStock('KTOS',  'Kratos Defense','defense',      30),
    ],
  },
];
